### PR TITLE
Cache'ing plots and table

### PR DESCRIPTION
**Pull request by krystian8207**
@PaulC91 

I added an option for cache'ing plots and table rendering.
I tested it out locally, but not on the server side so I'm not sure if this works correctly with the shiny server.

If you have an option to test it out on a staging server that would be great. I mostly wonder about `.rcache` paths for crone and inside `mod_map` module. If you need any help with this please let me know. I'll be available on Monday.

cache

### CODE REVIEW

**Comment by PaulC91** [comment]
Hi @krystian8207 

I deployed this PR here: https://reports.msf.net/public/covid19-testing/

Seems to me that the .rcache path is working fine! Let me know if you can spot any problems.

Thanks,
Paul

**Comment by krystian8207** [comment]
@PaulC91 
I tested it out now. Could you check if .rcache files were updated?
Did you also check whether .rcache files are removed correctly after cron job update? If so I think we can merge the change.

**Comment by PaulC91** [comment]
Yes all working well! 
Could you just change `dev/.rcache/*` in the .gitignore to `.rcache/*` then I will merge.
Thanks.

**Comment by krystian8207** [comment]
@PaulC91 That's great. I already pushed the requested change.

**Pull request merged**
