### PR TITLE
Table and plots initial optimization.

### PR DESCRIPTION
**Pull request by krystian8207**
This is Appsilon's initial approach to app optimization.

What has changed:
* Expand row details function for the table was moved from R to JS. This way it works > 4 secs faster. The only difference is that the change shows expand icons every time, so I display specific information when no data was available to display there. Probably there is an option to improve this but I couldn't find a simple solution.
* For plots `highcharter::hchart` was replaced with more low-level functions and data serialization was done by custom one that is ~2.5 secs faster.

Here you can see the final result:
output

### CODE REVIEW

**Comment by PaulC91** [comment]
Hi Krystian. This is great, thanks a lot. 

A 4 second improvement by switching to JS on expand rows is very interesting!

The only issue I can see is that the labels on the highcharts date axis are not formatted as dates anymore. Ready for a merge if we can fix this!

Thanks again,
Paul

**Comment by krystian8207** [comment]
@PaulC91 let me take a look at axis labels issue. Could you provide which versions packages do use use in the application? `renv.lock` or `manifest.json` file would be very helpful here.

About using JS on rows expanding, please verify if the default message when no comments are available in the data is correct from the UX perspective and meet your expectations.

**Comment by krystian8207** [comment]
@PaulC91 I pushed one commit with fixing the labels. ptal

**Comment by PaulC91** [comment]
I've added a `renv.lock` to the master branch. 

Date axis labels appear to be fixed but there's an issue with the daily cases/death chart now:

Screenshot 2020-05-26 at 14 59 29

**Comment by krystian8207** [comment]
@PaulC91 Thank you for spotting that. This would work fine now.

**Comment by PaulC91** [comment]
Yes looking good! thanks. 
Can we go with "No further information available" the default table expand message?

**Comment by krystian8207** [comment]
Sure, changed already.

**Pull request merged**
